# Generated by Django 3.1.4 on 2021-01-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='govern',
            field=models.CharField(choices=[('AlSharkia', 'AlSharkia'), ('Alexandria', 'Alexandria'), ('Cairo', 'Cairo')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
